### ISSUE TITLE
AttributeError: 'Pool' object has no attribute 'children'

### ISSUE THREAD

**Issue by davfarrugia** [mdavis-xyz/lambda_multiprocessing#4]
Trying to run a simple example with `apply_async`:

    with closing(Pool(2)) as pool:
        funclist = []

        for item in list_of_items:
            f = pool.apply_async(myfunc, [arg1, item, arg2])
            funclist.append(f)

        results = []
        for f in funclist:
            result = f.get(timeout=900)
            results.append(result)

        pool.close()
        pool.terminate()

This throws the error: AttributeError: 'Pool' object has no attribute 'children'.

**Comment by ogencoglu** [comment]
How is this solved? Does something like:

```
    with mp.Pool(processes=cfg_prod["n_workers"]) as pool:
            pool.apply_async(...)
```

work?

**Comment by mdavis-xyz** [comment]
What's the question?

This issue was closed a year ago. It's not clear to me what the problem is. @ogencoglu if you want help please provide a minimum working example. Some code I can copy-paste to get exactly the error you are facing.
