### ISSUE TITLE
[ERROR] AttributeError: 'Pool' object has no attribute 'children'

### ISSUE THREAD

**Issue by Luca-Blight** [mdavis-xyz/lambda_multiprocessing#5]
Odd error to receive, any ideas?

[ERROR] AttributeError: 'Pool' object has no attribute 'children'
Traceback (most recent call last):
  File "/var/task/main.py", line 201, in handler
    unnested_content_data = pool_one.map(unnest_data, content_data)
  File "/var/task/lambda_multiprocessing/main.py", line 315, in map
    return self.starmap(func, zip(iterable), chunksize, callback, error_callback)
  File "/var/task/lambda_multiprocessing/main.py", line 325, in starmap
    results = self.starmap_async(func, iterable, chunksize, callback, error_callback)
  File "/var/task/lambda_multiprocessing/main.py", line 322, in starmap_async
    return [self.apply_async(func, args) for args in iterable]
  File "/var/task/lambda_multiprocessing/main.py", line 322, in <listcomp>
    return [self.apply_async(func, args) for args in iterable]
  File "/var/task/lambda_multiprocessing/main.py", line 305, in apply_async
    for c in self.children:

**Comment by mdavis-xyz** [comment]
Hmm, strange.

Can you share the code you used to produce this error?

**Comment by mdavis-xyz** [comment]
Thanks for the MWE. Hmm yes it looks like the interface to this library is slightly different to the standard library one.

For now, just swap to the `with` approach, which will implicitly call `__enter__`. Which will create `.children`.

```
with ThreadPool(3) as pool:
    pool.map(partial(test_def, test_str), test_list)
```

(Also note that `return` is a statement not a function. So you should say `return True` not `return(True)`. But that's unrelated.)

**Comment by BylgakovAN** [comment]
Thank you.

Everything works fine with the context manager.

I wish your library development.

P.S.
> (Also note that return is a statement not a function. So you should say return True not return(True). But that's unrelated.)

I'm not a real programmer :)
