### ISSUE TITLE
Package is missing py.typed flag

### ISSUE THREAD

**Issue by ryanc-bs** [mdavis-xyz/lambda_multiprocessing#9]
Thanks for creating this package. The only issue I had in using it is that mypy cannot correctly use the type information, from looking at the code it seems to be because there is no `py.typed` file present. I'm happy to raise a PR to add this if you like.

**Comment by mdavis-xyz** [comment]
I have not used mypy before. I don't know what a py.typed file is. How is it better than inline annotations?

Aren't most of the annotations just going to be something extremely generic like Iterable[Any] ?

But yeah, if you want to raise a PR I'll merge it.

Just FYI I'm not working in this space at the moment, and am quite busy for the next few weeks. So I might respond slowly.

**Comment by ryanc-bs** [comment]
no worries. py.typed doesn't replace the existing annotations, it is just an empty flag file. It indicates to code which installs this package that there are type annotations present, annoyingly without it mypy refuses to acknowledge or understand. the types of the package interface. No worries, I'll raise a quick PR, should only be small.
